name: Reusable Create Video workflow
on:
  workflow_call:
    inputs:
      video-folder:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: narakeet/build-video-github-action@v1.0.5
      id: video
      with:
        source-path: ${{inputs.video-folder}}/script.md
        github-token: ${{ secrets.GITHUB_TOKEN }}
        api-key: ${{ secrets.NARAKEET_API_KEY }}

    - uses: actions/upload-artifact@v4
      with:
        name: video
        path: 
          ${{ steps.video.outputs.video-file }}

    - uses: actions/upload-artifact@v4
      with:
        name: subtitles
        path: 
          ${{ steps.video.outputs.srt-file }}

    - uses: actions/upload-artifact@v4
      with:
        name: poster
        path: 
          ${{ steps.video.outputs.poster-file }}